name: modern_flutter
description: Modern Flutter App Structure

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bottom_navy_bar: ^5.3.2
  cached_network_image: ^2.2.0+1
  cloud_firestore: ^0.14.2
  cupertino_icons: ^1.0.0
  dartx: ^0.5.0
  dio: ^3.0.9
  dough: ^0.3.6
  firebase_analytics: ^6.2.0
  firebase_core: ^0.5.2
  firebase_crashlytics: ^0.2.3
  firebase_messaging: ^7.0.3
  flutter_cache_manager: ^2.0.0
  flutter_launcher_icons: ^0.8.1
  flutter_local_notifications: ^3.0.2
  flutter_screenutil: ^4.0.2+3
  flutter_svg: ^0.19.1
  fluttertoast: ^7.1.1
  get_it: ^5.0.1
  lint: ^1.5.1
  logger: ^0.9.2
  path: ^1.7.0
  path_provider: ^1.6.11
  photo_view: ^0.10.2
  polygon_clipper: ^1.0.2
  provider: ^4.3.1
  settings_ui: ^0.5.0
  share: ^0.6.4+3
  shared_preferences: ^0.5.8

dependency_overrides:
  flutter_local_notifications: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppin/Poppins-Black.ttf
        - asset: assets/fonts/poppin/Poppins-Bold.ttf
        - asset: assets/fonts/poppin/Poppins-Light.ttf
        - asset: assets/fonts/poppin/Poppins-Medium.ttf
        - asset: assets/fonts/poppin/Poppins-Regular.ttf
        - asset: assets/fonts/poppin/Poppins-SemiBold.ttf
        - asset: assets/fonts/poppin/Poppins-Thin.ttf
