name: modern_flutter
description: Modern Flutter App Structure

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.8
  cached_network_image: ^2.0.0
  provider: ^4.3.1
  get_it: ^4.0.0
  fluttertoast: ^6.0.1
  share: ^0.6.4+3
  dio: ^3.0.9
  alice: ^0.1.1
  flutter_local_notifications: ^1.4.4+2
  flutter_screenutil: ^2.2.0
  flutter_launcher_icons: ^0.7.5
  flutter_cache_manager: ^1.4.1
  path_provider: ^1.6.11
  path: ^1.6.4
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.16
  firebase_crashlytics: ^0.1.3
  cloud_firestore: ^0.13.7
  location: ^3.0.2
  logger: ^0.9.1
  flutter_svg: ^0.18.0
  polygon_clipper: ^1.0.2
  bottom_navy_bar: ^5.3.2
  dough: ^0.2.2
  settings_ui: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppin/Poppins-Black.ttf
        - asset: assets/fonts/poppin/Poppins-Bold.ttf
        - asset: assets/fonts/poppin/Poppins-Light.ttf
        - asset: assets/fonts/poppin/Poppins-Medium.ttf
        - asset: assets/fonts/poppin/Poppins-Regular.ttf
        - asset: assets/fonts/poppin/Poppins-SemiBold.ttf
        - asset: assets/fonts/poppin/Poppins-Thin.ttf