name: modern_flutter
description: Modern Flutter App Structure

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.8
  cached_network_image: ^2.2.0+1
  provider: ^4.3.1
  get_it: ^5.0.1
  fluttertoast: ^7.1.1
  share: ^0.6.4+3
  dio: ^3.0.9
  # alice: ^0.1.5
  flutter_local_notifications: ^3.0.1+2
  flutter_screenutil: ^3.2.0
  flutter_launcher_icons: ^0.8.1
  flutter_cache_manager: ^2.0.0
  path_provider: ^1.6.11
  path: ^1.7.0
  firebase_core: ^0.5.1
  firebase_analytics: ^6.1.0
  firebase_crashlytics: ^0.2.2
  cloud_firestore: ^0.14.2
  location: ^3.0.2
  logger: ^0.9.2
  flutter_svg: ^0.19.1
  polygon_clipper: ^1.0.2
  bottom_navy_bar: ^5.3.2
  dough: ^0.3.6
  settings_ui: ^0.4.0
  photo_view: ^0.10.2

dependency_overrides:
  flutter_local_notifications: 3.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppin/Poppins-Black.ttf
        - asset: assets/fonts/poppin/Poppins-Bold.ttf
        - asset: assets/fonts/poppin/Poppins-Light.ttf
        - asset: assets/fonts/poppin/Poppins-Medium.ttf
        - asset: assets/fonts/poppin/Poppins-Regular.ttf
        - asset: assets/fonts/poppin/Poppins-SemiBold.ttf
        - asset: assets/fonts/poppin/Poppins-Thin.ttf