name: modern_flutter
description: Modern Flutter App Structure

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6+2
  cached_network_image: ^2.0.0
  flutter_cache_manager: ^1.1.3
  provider: ^4.0.4
  get_it: ^4.0.0
  fluttertoast: ^3.1.3
  share: ^0.6.3+6
  dio: ^3.0.9
  alice: ^0.0.23
  flutter_local_notifications: ^1.2.0+4
  flutter_screenutil: ^1.0.2
  path_provider: ^1.6.1
  path: ^1.6.4
  firebase_core: ^0.4.4+2
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3
  cloud_firestore: ^0.13.4
  location: ^2.3.5
  logger: ^0.8.3
  flutter_svg: ^0.17.2
  polygon_clipper: ^1.0.2
  bottom_navy_bar: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppin/Poppins-Black.ttf
        - asset: assets/fonts/poppin/Poppins-Bold.ttf
        - asset: assets/fonts/poppin/Poppins-Light.ttf
        - asset: assets/fonts/poppin/Poppins-Medium.ttf
        - asset: assets/fonts/poppin/Poppins-Regular.ttf
        - asset: assets/fonts/poppin/Poppins-SemiBold.ttf
        - asset: assets/fonts/poppin/Poppins-Thin.ttf